name: sutori
version: 0.1.0
github: MathiasSM/Sutori
license: BSD3
author:
  - Mathias San Miguel <mathiassanmiguel@gmail.com>
  - Génesis Kufatty <gdkufatty@gmail.com>
maintainer:
  - Mathias San Miguel <mathiassanmiguel@gmail.com>
  - Génesis Kufatty <gdkufatty@gmail.com>
copyright:
  - (c) 2018 Mathias San Miguel
  - (c) 2018 Génesis Kufatty

extra-source-files:
  - src/Lexer.x
  - README.md
  - GRAMMAR.md
  - ChangeLog.md

synopsis: Front-end for Sutori language compiler
category: Language

description: 'Please see the README on GitHub at <https://github.com/MathiasSM/Sutori#readme>'

dependencies:
  - base >= 4.7 && < 5
  - array

library:
  source-dirs: src

executables:
  sutori:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sutori

tests:
  sutori-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sutori

