name: sutori
version: 0.2.4
github: MathiasSM/Sutori
license: BSD3
author:
  - "Mathias San Miguel <mathiassanmiguel@gmail.com>"
  - "Génesis Kufatty <gdkufatty@gmail.com>"
maintainer:
  - "Mathias San Miguel <mathiassanmiguel@gmail.com>"
  - "Génesis Kufatty <gdkufatty@gmail.com>"
copyright:
  - (c) 2018 Mathias San Miguel
  - (c) 2018 Génesis Kufatty

synopsis: Sutori language compiler
category: Compilers/Interpreters

description: 'Please see the README on GitHub at <https://github.com/MathiasSM/Sutori#readme>'

extra-source-files:
  - src/Sutori/Lexer/Lexer.x
  - src/Sutori/Parser/Parser.y
  - README.md
  - ChangeLog.md

dependencies:
  - base >= 4.7 && < 5
  - array
  - mtl
  - vector
  - containers
  - hspec
  - QuickCheck

build-tools:
  - alex
  - happy

library:
  source-dirs: src

executables:
  sutori:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fwarn-tabs
      - -fwarn-unused-imports
      - -fwarn-missing-signatures
      - -fwarn-name-shadowing
      - -fwarn-incomplete-patterns
    dependencies:
      - sutori

tests:
  sutori-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sutori

